# The URL the site will be built for
base_url = "https://mintyfresh.love"

title = "mintyfresh dot love"
description = "Portfolio page of Mint Raines"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# The default language; used in feeds.
default_language = "en"

[extra]
# User settings
username = "Mint Raines"
user_description = """You've found Mint Raines' web page.\n
I'm a cybersecurity-trained software engineer from Melbourne, Australia.
I've spent the last two years honing various skills while recovering from severe anxiety.
You've probably come here looking for some of them, so here they are!"""
user_title = "Personal Portfolio"
user_email = "hi@mintyfresh.love"
twitch_username = "chamomileTeacup_"
github_username =  "verymintyfresh"
bsky_username =  "mintyfresh.love"

# Google-analytics
google_analytics.id = ""
